{% set version = "1.6.0" %}

package:
  name: astunparse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/astunparse/astunparse-{{ version }}.tar.gz
  sha256: 1dae2a4c53e9bc6201dd7d6c08b318abf67a1150c40de116a7ea12997472036b

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six >=1.6.1,<2.0

test:
  imports:
    - astunparse

about:
  home: https://github.com/simonpercivall/astunparse
  license: BSD 3-Clause, PSF 2
  license_file: LICENSE
  summary: An AST unparser for Python.
  description: |
    This is a factored out version of unparse found in the Python source
    distribution; under Demo/parser in Python 2 and under Tools/parser in
    Python 3.
  dev_url: https://github.com/simonpercivall/astunparse
  doc_url: http://astunparse.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - goanpeca
